/**
 * ============================================================
 * CONTENIDO: Sub-productos / referencias de Mobiliario Exterior
 * ============================================================
 * 🔌 Sanity: *[_type == "mobiliarioItem" && category == $category]
 * ============================================================
 */

import { ClipboardList, Palette, Truck, Wrench } from "lucide-react";
import type { ProductLandingData } from "@/components/ProductLanding";

import ventaImg from "@/assets/venta-mobiliario.jpg";
import project1 from "@/assets/project-1.jpg";
import project2 from "@/assets/project-2.jpg";
import project3 from "@/assets/project-3.jpg";

const sharedProcess: ProductLandingData["process"] = [
  { icon: ClipboardList, title: "Asesoría", description: "Evaluamos tu espacio y necesidades." },
  { icon: Palette, title: "Selección", description: "Elige configuración, color y materiales." },
  { icon: Truck, title: "Entrega", description: "Envío directo a tu ubicación." },
  { icon: Wrench, title: "Armado", description: "Ensamblaje profesional incluido." },
];

/** Sub-productos por categoría de mobiliario */
export const mobiliarioItems: Record<string, Record<string, ProductLandingData>> = {
  "salas-exterior": {
    "sofia-modular": {
      breadcrumb: "Mobiliario · Salas · Sofía Modular",
      title: "Sofá",
      highlight: "Sofía Modular",
      description: "Set modular en ratán sintético PE con cojines Sunbrella. Configura a tu medida.",
      heroImage: { src: ventaImg, alt: "Sofá Sofía Modular" },
      introTitle: "Modularidad para tu",
      introHighlight: "terraza",
      introText: "El set Sofía Modular permite crear la configuración perfecta para tu espacio exterior. Cada módulo se conecta de forma independiente, permitiendo diseños en L, U o lineal. Estructura de aluminio con tejido de ratán PE resistente a UV.",
      introImage: { src: ventaImg, alt: "Sofía Modular detalle" },
      benefits: ["Módulos independientes", "Ratán sintético PE anti-UV", "Cojines Sunbrella impermeables", "Estructura aluminio", "Configuración en L, U o lineal", "Garantía 5 años"],
      process: sharedProcess,
      gallery: [{ src: ventaImg, alt: "Sofía Modular 1" }, { src: project1, alt: "Sofía Modular 2" }],
      faqs: [
        { question: "¿Cuántos módulos necesito?", answer: "Depende de tu espacio. Un set básico de 3 módulos cubre un área de 2.5m. Te asesoramos para la configuración ideal." },
        { question: "¿Se pueden comprar módulos adicionales?", answer: "Sí, cada módulo se vende por separado para que amplíes tu set cuando quieras." },
      ],
      parentCategory: { label: "Salas de Exterior", href: "/productos/mobiliario-exterior/salas-exterior" },
      formContext: "Salas Exterior - Sofía Modular",
      productName: "Sofá Sofía Modular",
    },
    "set-bali": {
      breadcrumb: "Mobiliario · Salas · Set Bali",
      title: "Set",
      highlight: "Bali",
      description: "Conjunto de sala exterior estilo resort con mesa de centro y cojines premium.",
      heroImage: { src: project1, alt: "Set Bali" },
      introTitle: "Estilo resort en tu",
      introHighlight: "jardín",
      introText: "El Set Bali trae la experiencia de un resort de lujo a tu hogar. Incluye sofá de 3 puestos, 2 sillones individuales y mesa de centro con vidrio templado. Tejido en ratán natural con tratamiento weather-proof.",
      introImage: { src: project1, alt: "Set Bali detalle" },
      benefits: ["Estilo resort de lujo", "Sofá 3 puestos + 2 sillones", "Mesa con vidrio templado", "Ratán natural tratado", "Cojines de secado rápido", "Fácil ensamblaje"],
      process: sharedProcess,
      gallery: [{ src: project1, alt: "Set Bali 1" }, { src: ventaImg, alt: "Set Bali 2" }],
      faqs: [
        { question: "¿El Set Bali resiste la lluvia?", answer: "Sí, el ratán tiene tratamiento impermeabilizante y los cojines son de secado rápido." },
      ],
      parentCategory: { label: "Salas de Exterior", href: "/productos/mobiliario-exterior/salas-exterior" },
      formContext: "Salas Exterior - Set Bali",
      productName: "Set Bali",
    },
    "sofa-capri": {
      breadcrumb: "Mobiliario · Salas · Sofá Capri",
      title: "Sofá",
      highlight: "Capri",
      description: "Sofá compacto de 2 puestos ideal para balcones y terrazas pequeñas.",
      heroImage: { src: project2, alt: "Sofá Capri" },
      introTitle: "Confort en espacios",
      introHighlight: "compactos",
      introText: "El Sofá Capri está diseñado para balcones y terrazas donde el espacio es limitado pero el estilo no se negocia. Compacto, ligero y con cojines de alta densidad para máximo confort.",
      introImage: { src: project2, alt: "Sofá Capri detalle" },
      benefits: ["Ideal para balcones", "Ligero y fácil de mover", "Cojines alta densidad", "Aluminio resistente", "Diseño compacto elegante", "Apilable para almacenamiento"],
      process: sharedProcess,
      gallery: [{ src: project2, alt: "Capri 1" }, { src: project3, alt: "Capri 2" }],
      faqs: [
        { question: "¿Qué medidas tiene?", answer: "140cm de ancho x 75cm de profundidad x 80cm de alto. Ideal para espacios desde 4m²." },
      ],
      parentCategory: { label: "Salas de Exterior", href: "/productos/mobiliario-exterior/salas-exterior" },
      formContext: "Salas Exterior - Sofá Capri",
      productName: "Sofá Capri",
    },
  },

  "comedores-terraza": {
    "mesa-toscana": {
      breadcrumb: "Mobiliario · Comedores · Mesa Toscana",
      title: "Mesa",
      highlight: "Toscana",
      description: "Mesa de comedor para 6 personas en teca maciza con acabado natural resistente.",
      heroImage: { src: project2, alt: "Mesa Toscana" },
      introTitle: "Elegancia natural en tu",
      introHighlight: "terraza",
      introText: "La Mesa Toscana en teca maciza certificada es la pieza central perfecta para comedores de exterior. Su acabado natural envejece con gracia, desarrollando una pátina plateada que le da carácter con el paso del tiempo.",
      introImage: { src: project2, alt: "Mesa Toscana detalle" },
      benefits: ["Teca maciza certificada", "Para 6 personas", "Acabado natural", "Resistente a la intemperie", "Extensión opcional a 8", "Bajo mantenimiento"],
      process: sharedProcess,
      gallery: [{ src: project2, alt: "Toscana 1" }, { src: ventaImg, alt: "Toscana 2" }],
      faqs: [
        { question: "¿La teca necesita mantenimiento?", answer: "Mínimo. Puede dejarse al natural o aplicar aceite de teca 1-2 veces al año para mantener el color original." },
      ],
      parentCategory: { label: "Comedores de Terraza", href: "/productos/mobiliario-exterior/comedores-terraza" },
      formContext: "Comedores - Mesa Toscana",
      productName: "Mesa Toscana",
    },
    "set-riviera": {
      breadcrumb: "Mobiliario · Comedores · Set Riviera",
      title: "Set",
      highlight: "Riviera",
      description: "Comedor completo para 4 personas en aluminio con sillas apilables y mesa de vidrio.",
      heroImage: { src: project3, alt: "Set Riviera" },
      introTitle: "Practicidad con",
      introHighlight: "estilo",
      introText: "El Set Riviera incluye mesa con tapa de vidrio templado y 4 sillas apilables en aluminio texturizado. Perfecto para terrazas donde se necesita un comedor funcional, resistente y fácil de almacenar.",
      introImage: { src: project3, alt: "Set Riviera detalle" },
      benefits: ["Mesa vidrio templado", "4 sillas apilables", "Aluminio texturizado", "Ultra liviano", "Resistente a corrosión", "Colores: grafito, blanco, arena"],
      process: sharedProcess,
      gallery: [{ src: project3, alt: "Riviera 1" }, { src: project1, alt: "Riviera 2" }],
      faqs: [
        { question: "¿Las sillas se apilan?", answer: "Sí, las 4 sillas se apilan para ahorrar espacio cuando no se usan." },
      ],
      parentCategory: { label: "Comedores de Terraza", href: "/productos/mobiliario-exterior/comedores-terraza" },
      formContext: "Comedores - Set Riviera",
      productName: "Set Riviera",
    },
    "comedor-industrial": {
      breadcrumb: "Mobiliario · Comedores · Comedor Industrial",
      title: "Comedor",
      highlight: "Industrial",
      description: "Mesa en polywood efecto madera con estructura de acero y bancas laterales.",
      heroImage: { src: ventaImg, alt: "Comedor Industrial" },
      introTitle: "Carácter urbano al",
      introHighlight: "aire libre",
      introText: "El Comedor Industrial combina la estética de un loft con la resistencia necesaria para exteriores. Mesa tipo picnic en polywood con efecto madera natural y estructura de acero galvanizado. Ideal para jardines, terrazas y restaurantes.",
      introImage: { src: ventaImg, alt: "Comedor Industrial detalle" },
      benefits: ["Polywood efecto madera", "Acero galvanizado", "Para 6-8 personas", "Estilo industrial-rústico", "Resistente a todo clima", "Ideal uso comercial"],
      process: sharedProcess,
      gallery: [{ src: ventaImg, alt: "Industrial 1" }, { src: project2, alt: "Industrial 2" }],
      faqs: [
        { question: "¿Sirve para restaurantes?", answer: "Sí, esta línea tiene garantía comercial para uso intensivo en restaurantes, bares y hoteles." },
      ],
      parentCategory: { label: "Comedores de Terraza", href: "/productos/mobiliario-exterior/comedores-terraza" },
      formContext: "Comedores - Comedor Industrial",
      productName: "Comedor Industrial",
    },
  },

  camastros: {
    "tumbona-mykonos": {
      breadcrumb: "Mobiliario · Camastros · Tumbona Mykonos",
      title: "Tumbona",
      highlight: "Mykonos",
      description: "Tumbona reclinable con ruedas en aluminio blanco y cojín de secado rápido.",
      heroImage: { src: ventaImg, alt: "Tumbona Mykonos" },
      introTitle: "Relax junto a la",
      introHighlight: "piscina",
      introText: "La Tumbona Mykonos combina diseño mediterráneo con funcionalidad total. Respaldo ajustable en 5 posiciones, ruedas para fácil movimiento y cojín de espuma de célula abierta que drena el agua en minutos.",
      introImage: { src: ventaImg, alt: "Mykonos detalle" },
      benefits: ["5 posiciones de reclinado", "Ruedas integradas", "Cojín secado rápido", "Aluminio blanco mate", "Apilable", "Resistente al cloro"],
      process: sharedProcess,
      gallery: [{ src: ventaImg, alt: "Mykonos 1" }, { src: project1, alt: "Mykonos 2" }],
      faqs: [{ question: "¿Resiste el cloro?", answer: "Sí, tanto la estructura como el cojín están diseñados para uso junto a piscinas cloradas." }],
      parentCategory: { label: "Camastros y Daybeds", href: "/productos/mobiliario-exterior/camastros" },
      formContext: "Camastros - Tumbona Mykonos",
      productName: "Tumbona Mykonos",
    },
    "daybed-bali": {
      breadcrumb: "Mobiliario · Camastros · Daybed Bali",
      title: "Daybed",
      highlight: "Bali",
      description: "Cama balinesa con dosel retráctil en ratán sintético y cojines premium.",
      heroImage: { src: project3, alt: "Daybed Bali" },
      introTitle: "Tu rincón de",
      introHighlight: "descanso",
      introText: "El Daybed Bali es la pieza estrella para zonas de descanso al aire libre. Con dosel retráctil para protección solar, estructura en ratán sintético y colchón de alta densidad con funda impermeable.",
      introImage: { src: project3, alt: "Daybed Bali detalle" },
      benefits: ["Dosel retráctil", "Colchón alta densidad", "Funda impermeable", "Ratán sintético PE", "Para 2 personas", "Cortinas laterales opcionales"],
      process: sharedProcess,
      gallery: [{ src: project3, alt: "Daybed 1" }, { src: ventaImg, alt: "Daybed 2" }],
      faqs: [{ question: "¿Se puede usar sin dosel?", answer: "Sí, el dosel es completamente retráctil y removible." }],
      parentCategory: { label: "Camastros y Daybeds", href: "/productos/mobiliario-exterior/camastros" },
      formContext: "Camastros - Daybed Bali",
      productName: "Daybed Bali",
    },
  },

  sombrillas: {
    "parasol-santorini": {
      breadcrumb: "Mobiliario · Sombrillas · Parasol Santorini",
      title: "Parasol",
      highlight: "Santorini",
      description: "Parasol de brazo lateral de 3.5m con rotación 360° y protección UV 50+.",
      heroImage: { src: project3, alt: "Parasol Santorini" },
      introTitle: "Sombra total con",
      introHighlight: "rotación 360°",
      introText: "El Parasol Santorini ofrece cobertura de 3.5m con brazo lateral que permite rotar 360° para seguir el sol durante todo el día. Lona acrílica con protección UV 50+ y estructura de aluminio reforzado.",
      introImage: { src: project3, alt: "Santorini detalle" },
      benefits: ["3.5m de diámetro", "Rotación 360°", "UV 50+", "Aluminio reforzado", "Manivela fácil", "Base con ruedas incluida"],
      process: sharedProcess,
      gallery: [{ src: project3, alt: "Santorini 1" }, { src: project2, alt: "Santorini 2" }],
      faqs: [{ question: "¿Qué base necesito?", answer: "Incluye base con ruedas de 50kg. Para zonas ventosas recomendamos anclarla al piso." }],
      parentCategory: { label: "Sombrillas y Parasoles", href: "/productos/mobiliario-exterior/sombrillas" },
      formContext: "Sombrillas - Parasol Santorini",
      productName: "Parasol Santorini",
    },
    "sombrilla-clasica": {
      breadcrumb: "Mobiliario · Sombrillas · Sombrilla Clásica",
      title: "Sombrilla",
      highlight: "Clásica",
      description: "Sombrilla de centro de 2.7m para mesa de comedor con poste de madera o aluminio.",
      heroImage: { src: project2, alt: "Sombrilla Clásica" },
      introTitle: "El complemento perfecto para tu",
      introHighlight: "comedor",
      introText: "La Sombrilla Clásica es el complemento esencial para mesas de comedor exterior. Disponible con poste de madera tropical o aluminio, en múltiples colores de lona acrílica impermeable.",
      introImage: { src: project2, alt: "Clásica detalle" },
      benefits: ["2.7m diámetro", "Poste madera o aluminio", "Lona acrílica impermeable", "Apertura con polea", "10+ colores disponibles", "Encaja en mesa con agujero central"],
      process: sharedProcess,
      gallery: [{ src: project2, alt: "Clásica 1" }, { src: ventaImg, alt: "Clásica 2" }],
      faqs: [{ question: "¿Qué tamaño de mesa cubre?", answer: "Una sombrilla de 2.7m cubre cómodamente mesas de hasta 1.5m de diámetro (4-6 personas)." }],
      parentCategory: { label: "Sombrillas y Parasoles", href: "/productos/mobiliario-exterior/sombrillas" },
      formContext: "Sombrillas - Sombrilla Clásica",
      productName: "Sombrilla Clásica",
    },
  },

  macetas: {
    "maceta-cilindrica": {
      breadcrumb: "Mobiliario · Macetas · Cilíndrica Fibra",
      title: "Maceta",
      highlight: "Cilíndrica",
      description: "Maceta cilíndrica en fibra de vidrio ultraliviana disponible en múltiples tamaños.",
      heroImage: { src: project1, alt: "Maceta Cilíndrica" },
      introTitle: "Elegancia vertical para tu",
      introHighlight: "jardín",
      introText: "La Maceta Cilíndrica en fibra de vidrio es perfecta para plantas altas y árboles ornamentales. Ultra liviana, resistente a heladas y disponible en acabado mate, brillante o texturizado en más de 15 colores.",
      introImage: { src: project1, alt: "Cilíndrica detalle" },
      benefits: ["Fibra de vidrio ultraliviana", "Resistente a heladas", "Drenaje integrado", "15+ colores", "Acabado mate/brillante", "Tamaños de 30cm a 1.2m"],
      process: sharedProcess,
      gallery: [{ src: project1, alt: "Cilíndrica 1" }, { src: project3, alt: "Cilíndrica 2" }],
      faqs: [{ question: "¿Se puede pintar?", answer: "Sí, la fibra de vidrio se puede pintar con cualquier color RAL. También ofrecemos servicio de personalización." }],
      parentCategory: { label: "Macetas y Jardineras", href: "/productos/mobiliario-exterior/macetas" },
      formContext: "Macetas - Cilíndrica Fibra",
      productName: "Maceta Cilíndrica",
    },
    "jardinera-rectangular": {
      breadcrumb: "Mobiliario · Macetas · Jardinera Rectangular",
      title: "Jardinera",
      highlight: "Rectangular",
      description: "Jardinera rectangular en cemento reforzado estilo industrial para separar ambientes.",
      heroImage: { src: project3, alt: "Jardinera Rectangular" },
      introTitle: "Divide espacios con",
      introHighlight: "verde",
      introText: "La Jardinera Rectangular en cemento reforzado es ideal como separador de ambientes en terrazas y jardines. Su peso aporta estabilidad y su acabado industrial combina con cualquier estilo de exterior.",
      introImage: { src: project3, alt: "Jardinera detalle" },
      benefits: ["Cemento reforzado", "Ideal como separador", "Acabado industrial", "Drenaje integrado", "Resistente a impactos", "Medidas personalizables"],
      process: sharedProcess,
      gallery: [{ src: project3, alt: "Jardinera 1" }, { src: project1, alt: "Jardinera 2" }],
      faqs: [{ question: "¿Son muy pesadas?", answer: "Sí, el cemento es pesado pero eso aporta estabilidad. Ofrecemos servicio de entrega y colocación incluido." }],
      parentCategory: { label: "Macetas y Jardineras", href: "/productos/mobiliario-exterior/macetas" },
      formContext: "Macetas - Jardinera Rectangular",
      productName: "Jardinera Rectangular",
    },
  },

  accesorios: {
    "cojines-sunbrella": {
      breadcrumb: "Mobiliario · Accesorios · Cojines Sunbrella",
      title: "Cojines",
      highlight: "Sunbrella",
      description: "Cojines decorativos de exterior en tela Sunbrella con más de 200 colores y patrones.",
      heroImage: { src: ventaImg, alt: "Cojines Sunbrella" },
      introTitle: "Color y confort para tu",
      introHighlight: "exterior",
      introText: "Los Cojines Sunbrella son el estándar mundial en textiles de exterior. Resistentes a UV, agua, moho y manchas, mantienen su color y textura año tras año. Disponibles en más de 200 colores y patrones.",
      introImage: { src: ventaImg, alt: "Cojines detalle" },
      benefits: ["Tela Sunbrella certificada", "200+ colores y patrones", "Resistente UV y agua", "Anti-moho", "Lavables a máquina", "Garantía 5 años en tela"],
      process: sharedProcess,
      gallery: [{ src: ventaImg, alt: "Cojines 1" }, { src: project2, alt: "Cojines 2" }],
      faqs: [{ question: "¿Se hacen a medida?", answer: "Sí, fabricamos cojines a medida para cualquier mueble de exterior." }],
      parentCategory: { label: "Accesorios de Exterior", href: "/productos/mobiliario-exterior/accesorios" },
      formContext: "Accesorios - Cojines Sunbrella",
      productName: "Cojines Sunbrella",
    },
    "iluminacion-solar": {
      breadcrumb: "Mobiliario · Accesorios · Iluminación Solar",
      title: "Iluminación",
      highlight: "Solar LED",
      description: "Lámparas y guirnaldas solares LED para ambientar terrazas y jardines sin cables.",
      heroImage: { src: project1, alt: "Iluminación Solar" },
      introTitle: "Ambienta sin",
      introHighlight: "cables",
      introText: "Nuestra línea de iluminación solar LED permite crear ambientes mágicos en tu exterior sin necesidad de instalación eléctrica. Desde guirnaldas decorativas hasta lámparas de piso y faroles solares con sensor de oscuridad.",
      introImage: { src: project1, alt: "Iluminación detalle" },
      benefits: ["100% energía solar", "Sin cables ni instalación", "Sensor de oscuridad", "LED cálido 3000K", "8-12 horas de autonomía", "Resistente a agua IP65"],
      process: sharedProcess,
      gallery: [{ src: project1, alt: "Iluminación 1" }, { src: project3, alt: "Iluminación 2" }],
      faqs: [{ question: "¿Funcionan en días nublados?", answer: "Sí, los paneles cargan con luz difusa. La autonomía puede ser menor (6-8h) en días muy nublados." }],
      parentCategory: { label: "Accesorios de Exterior", href: "/productos/mobiliario-exterior/accesorios" },
      formContext: "Accesorios - Iluminación Solar",
      productName: "Iluminación Solar LED",
    },
  },
};
